Feature: generated_coupon

Scenario:
A New system has been released to book hotels, car and tours.
Given I am on admin Login home page
When I provide username as "admin@phptravels.com" And I enter password as "demoadmin" to login
And user go to the coupon page
When user add a new coupon with a manual code
When a new coupon is added with a autogenerated code
And both coupon should be visible

Scenario:
Both coupon created should be displayed and be available
Given user enter to home page
And coupon created automatacally and manually are used
Then both books can be visible on the account
