Feature: generated_coupon

@CreateNewCoupons
Scenario:
A New system has been released to book hotels, car and tours.
Given I am on admin Login home page
When I provide username as "admin@phptravels.com" And I enter password as "demoadmin" to login
And user go to the coupon page
When user add a new coupon with a manual code
	| 75 | 2 | Manual |
When a new coupon is added with a autogenerated code
	| 45 | 5 | Auto |
And both coupon should be visible

@UseCoupons
Scenario:
Both coupon created should be displayed and be available
Given user enter to home page
| user@phptravels.com | demouser |
And coupon created automatacally and manually are used
 | Manual | Auto |
Then both books can be visible on the account
