package Coupon;

import org.openqa.selenium.chrome.*;
import cucumber.api.PendingException;
import cucumber.api.java.en.*;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;

public class generatedCoupon_Steps {
	
	WebDriver driver;
	static String codeCoupon;
	static String idBook1, idBook2, codeBook1, codeBook2;
	
	
	@Given("^I am on admin Login home page$")
	public void i_am_on_admin_Login_home_page() throws Throwable {
		System.setProperty("webdriver.chrome.driver", "src\\test\\resources\\chromedriver_win32\\chromedriver.exe");
		driver = new ChromeDriver();
		driver.navigate().to(" http://www.phptravels.net/admin");
		driver.manage().window().maximize();
//	    throw new PendingException();
	}
	
	@When("^I provide username as \"([^\"]*)\" And I enter password as \"([^\"]*)\" to login$")
	public void i_provide_username_as_And_I_enter_password_as_to_login(String arg1, String arg2) throws Throwable {
		//Login
		driver.findElement(By.name("email")).sendKeys(arg1);
		driver.findElement(By.name("password")).sendKeys(arg2);
		driver.findElement(By.className("btn-primary")).click();
//	    throw new PendingException();
	}
		
	@And("^user go to the coupon page$")
	public void user_go_to_the_coupon_page() throws Throwable {
		driver.navigate().refresh();
		driver.findElement(By.partialLinkText("Coupons")).click();
//		    throw new PendingException();
	}
	
	@When("^user add a new coupon with a manual code$")
	public void user_add_a_new_coupon_with_a_manual_code() throws Throwable {
		driver.findElement(By.xpath("//*[@id='content']/div[1]/div[2]/div[1]/button")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//*[@id='rate']")).sendKeys("75");
		driver.findElement(By.name("max")).sendKeys("2");
		driver.findElement(By.name("code")).sendKeys("Manual");
		driver.findElement(By.xpath("//*[@id='ADD_COUPON']/div[2]/div/div[2]/div[3]/button")).click();
		Thread.sleep(2000);
//	    throw new PendingException();
	}

	@When("^a new coupon is added with a autogenerated code$")
	public void a_new_coupon_is_added_with_a_autogenerated_code() throws Throwable {
		driver.findElement(By.xpath("//*[@id='content']/div[1]/div[2]/div[1]/button")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//*[@id='rate']")).sendKeys("45");
		driver.findElement(By.name("max")).sendKeys("5");
		driver.findElement(By.id("add")).click();
		Thread.sleep(1000);
		codeCoupon = driver.findElement(By.name("code")).getAttribute("value");
		driver.findElement(By.xpath("//*[@id='ADD_COUPON']/div[2]/div/div[2]/div[3]/button")).click();
		Thread.sleep(2000);
//	    throw new PendingException();
	}

	@And("^both coupon should be visible$")
	public void both_coupon_should_be_visible() throws Throwable {
		String coupon1 = driver.findElement(By.xpath("//*[@id='content']/div[1]/div[2]/div[2]/div/div[1]/div[2]/table/tbody/tr[1]/td[4]\r\n")).getText();
		String coupon2 = driver.findElement(By.xpath("//*[@id='content']/div[1]/div[2]/div[2]/div/div[1]/div[2]/table/tbody/tr[2]/td[4]\r\n")).getText();
		if(coupon1.equals(codeCoupon) && coupon2.equals("Manual")) {
			System.out.println("Coupons created successfully");
		}
		else {
			System.out.println("Coupons were not created");
		}
		driver.close();	
	}

	@Given("^user enter to home page$")
	public void user_enter_to_home_page() throws Throwable {
		System.setProperty("webdriver.chrome.driver", "src\\test\\resources\\chromedriver_win32\\chromedriver.exe");
    	driver = new ChromeDriver(); 
    	driver.navigate().to("http://www.phptravels.net/");
    	driver.manage().window().maximize();
    	
    	driver.findElement(By.xpath("/html/body/div[3]/div/div/div[2]/ul/ul/li[1]")).click();
	    driver.findElement(By.linkText("Login")).click();
	    
	    JavascriptExecutor jse = (JavascriptExecutor)driver;
    	jse.executeScript("window.scrollBy(0,250)", "");
    	Thread.sleep(1000);
		driver.findElement(By.name("username")).sendKeys("user@phptravels.com");
	    driver.findElement(By.name("password")).sendKeys("demouser");
	    driver.findElement(By.xpath("//*[@id='loginfrm']/div[1]/div[5]/button")).click();
//	    throw new PendingException();
	}

	@When("^coupon created automatacally and manually are used$")
	public void coupon_created_automatacally_and_manually_are_used() throws Throwable {
		//Manual
		Thread.sleep(2000);
		driver.findElement(By.xpath("/html/body/nav[1]/div/div/div/ul/li[2]/a")).click();
    	Thread.sleep(2000);
    	driver.findElement(By.partialLinkText("Rendezvous Hotels")).click();
    	driver.navigate().refresh();
    	JavascriptExecutor jse = (JavascriptExecutor)driver;
    	jse.executeScript("window.scrollBy(0,750)", "");
    	Thread.sleep(1000);
    	driver.findElement(By.xpath("//*[@id='ROOMS']/div/table/tbody/tr[1]/td/div[2]/div/div[5]/div[3]")).click();
    	
    	JavascriptExecutor jse2 = (JavascriptExecutor)driver;
    	jse2.executeScript("window.scrollBy(0,850)", "");
    	driver.findElement(By.xpath("//*[@id='bookingdetails']/div[5]/div[2]/div[2]/div[2]/input")).sendKeys("Manual");
    	driver.findElement(By.xpath("//*[@id='bookingdetails']/div[5]/div[2]/div[2]/div[3]/span")).click();
    	Thread.sleep(2000);
    	driver.findElement(By.name("logged")).click();
    	
    	Thread.sleep(5000);
    	driver.findElement(By.xpath("//*[@id='body-section']/div[1]/div/div[3]/center/button[1]")).click();
    	driver.switchTo().alert().accept();
    	idBook1 = driver.findElement(By.xpath("//*[@id=\"body-section\"]/div[1]/div/div[7]/div[1]/div[3]/span")).getText();
    	//codeBook1 = driver.findElement(By.xpath("//*[@id=\"body-section\"]/div[1]/div/div[5]/div[1]/div[3]/text()[2]")).getText();
    	Thread.sleep(2000);
    	
    	//Automatic
    	Thread.sleep(2000);
    	driver.findElement(By.xpath("/html/body/nav[1]/div/div/div/ul/li[2]/a")).click();
    	Thread.sleep(2000);
    	driver.findElement(By.partialLinkText("Rendezvous Hotels")).click();
    	driver.navigate().refresh();
    	JavascriptExecutor jse3 = (JavascriptExecutor)driver;
    	jse3.executeScript("window.scrollBy(0,750)", "");
    	Thread.sleep(1000);
    	driver.findElement(By.xpath("//*[@id='ROOMS']/div/table/tbody/tr[1]/td/div[2]/div/div[5]/div[3]")).click();
    	
    	JavascriptExecutor jse4 = (JavascriptExecutor)driver;
    	jse4.executeScript("window.scrollBy(0,850)", "");
    	driver.findElement(By.xpath("//*[@id='bookingdetails']/div[5]/div[2]/div[2]/div[2]/input")).sendKeys(codeCoupon);
    	driver.findElement(By.xpath("//*[@id='bookingdetails']/div[5]/div[2]/div[2]/div[3]/span")).click();
    	Thread.sleep(2000);
    	driver.findElement(By.name("logged")).click();
    	
    	Thread.sleep(5000);
    	driver.findElement(By.xpath("//*[@id='body-section']/div[1]/div/div[3]/center/button[1]")).click();
    	driver.switchTo().alert().accept();
    	idBook2 = driver.findElement(By.xpath("//*[@id=\"body-section\"]/div[1]/div/div[7]/div[1]/div[3]/span")).getText();
    	//codeBook2 = driver.findElement(By.xpath("//*[@id=\"body-section\"]/div[1]/div/div[5]/div[1]/div[3]/text()[2]")).getText();
    	Thread.sleep(2000);
//	    throw new PendingException();
	}

	@Then("^both books can be visible on the account$")
	public void both_books_can_be_visible_on_the_account() throws Throwable {
		driver.findElement(By.xpath("/html/body/div[3]/div/div/div[2]/ul/ul/li[1]")).click();
	    driver.findElement(By.linkText("Account")).click();
	    
	    if (driver.getPageSource().contains(idBook1) && driver.getPageSource().contains(idBook2)){
 	    	System.out.println("Both reserves with coupon were booked correctly");
 	    }else{
 	    	System.out.println("Test Failed");
 	    } 
//	    throw new PendingException();
	    driver.close();
	}
}
	
		
